version: 0.2

phases:
  pre_build:
    commands:
    - echo Prebuild command
    - pip install aws-sam-cli
  build:
    commands:
    - echo Build started on `date`
    - ls
    - cd java/functions/showMyIp
    - mvn clean install
    - cd -
    - cp java/functions/showMyIp/target/showMyIp-1.0-SNAPSHOT.jar build
    - echo aws cloudformation package --template-file template.yaml --kms-key-id $CODEBUILD_KMS_KEY_ID --s3-bucket  codepipeline-eu-west-1-997822486367 --output-template-file  packaged.yaml
  post_build:
    commands:
    - echo Build completed on `date`
    - echo aws cloudformation deploy --template packaged.yaml --stack-name aliasShifting --capabilities CAPABILITY_IAM
    - sam package     --template-file template.yaml     --output-template-file packaged.yaml     --s3-bucket  codepipeline-eu-west-1-997822486367
    - sam deploy     --template-file packaged.yaml     --stack-name aliasShifting     --capabilities CAPABILITY_IAM
artifacts:
  files: packaged.yaml
