version: 0.2

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
  build:
    commands:
    - echo Build started on `date`
    - sh build.sh
    - cp java/functions/showMyIp/target/showMyIp-1.0-SNAPSHOT.jar build
    - sam package     --template-file template.yaml     --output-template-file packaged.yaml     --s3-bucket  alias-lambda-taffic-shifting

  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files: packaged.yaml
