version: 0.2

phases:
  pre_build:
    commands:
    - echo Prebuild command
  build:
    commands:
    - echo Build started on `date`
    - ls
    - cd java/functions/showMyIp
    - mvn clean install
    - cd -
    - ls
    - cp java/functions/showMyIp/target/showMyIp-1.0-SNAPSHOT.jar build
    - echo aws cloudformation package --template-file template.yaml --s3-bucket --kms-key-id $KEY_ID codepipeline-eu-west-1-997822486367/lambda-blue-green > packaged.yaml
    - aws cloudformation package --template-file template.yaml --s3-bucket --kms-key-id $KEY_ID codepipeline-eu-west-1-997822486367/lambda-blue-green > packaged.yaml
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files: packaged.yaml
